on: workflow_dispatch

concurrency:
  group: build-${{ format('{0}-{1}', github.head_ref || github.run_number, github.job) }}
  cancel-in-progress: true

jobs:
  base:
    runs-on: ubuntu-20.04
    timeout-minutes: 90
    steps:
      - name: enable experimental docker features
        run: |
          sudo bash -c 'echo "{ \"cgroup-parent\": \"/actions_job\",\"experimental\":true}" > /etc/docker/daemon.json'
          sudo service docker restart
          docker version -f '{{.Server.Experimental}}'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build slim image
        run: |
          cd image && ruby auto_build.rb base_slim
      - name: build release image
        run: |
          cd image && ruby auto_build.rb base
      - name: tag images
        id: tag-images
        run: |
          docker tag kitabisa/discourse-base:build_slim kitabisa/discourse-base:slim
          docker tag kitabisa/discourse-base:build kitabisa/discourse-base:release
      - name: push to dockerhub
        run: |
          docker push kitabisa/discourse-base:slim
          docker push kitabisa/discourse-base:release